export const fitoSanitario = [
  {
    id: 1,
    nombre: 'Café',
    fichaTecnica: {
      'tabla#tabla-Programa Fitosanitario y Foliar Café': {
        headers: [
          'Análisis/Producto',
          'Presentación',
          'Frecuencia',
          'Dosis',
          'Dosis',
        ],
        rows: [
          ['Semilleros y Viveros'],
          ['Semilleros y Chapola (1 a 3 meses)'],
          ['Raizal', 'Kg', '2', '4 copas', '1 Kg'],
          ['Cycosin 50Sc', '250ml', '2', '2 copas', '0.5 L'],
          ['Microessential', '43kg', '1', '0.5 Onz / Planta', '1qq'],
          [''],
          ['Viveros (3 meses a 1 año)'],
          ['Raizal', 'Kg', '3', '4 copas', '1 Kg'],
          ['Triac', 'Litro', '3', '2 copas', '0.3 L'],
          ['Curyom 55EG', '100ml', '3', '10cc', '0.1 L'],
          ['Balear 72SC', 'Litro', '3', '2 copas', '0.5 L'],
          [''],
          ['Fertilización'],
          ['Plantía Fastrac 20-15-5', '43kg', '1', '2 Onz / Planta', '4qq'],
          [''],
          [''],
          ['Café Plantía (1 a 2 años)'],
          ['Fungicidas, Insecticidas y Foliares'],
          ['Break Thru 100SL', '120ml', '2', '6cc', '0.6 L'],
          ['Foltron Plus', 'Litro', '1', '4 copas', '1 L'],
          ['Poliquel Zinc', 'Litro', '1', '4 copas', '1 L'],
          ['Sergomil', 'Litro', '1', '2 copas', '0.5 L'],
          ['Opus 12.5SC', 'Litro', '2', '1/2 copa', '0.25 L'],
          ['Opera 18.3SE', 'Litro', '1', '1.5 copas', '0.4 L '],
          ['Curyom 55EC', '100ml', '2', '10cc', '0.1 L'],
          [''],
          ['Control de Malezas'],
          ['Biophase', '225cc', '2', '10cc', '0.1 L'],
          ['Glifo One 36SL', 'Litro', '2', '6 copas', '1.5 L'],
          [''],
          ['Fertilización'],
          ['Plantía Fastrac 20-15-5', '43kg', '1', '3 Onz / Planta', '6qq'],
          [''],
          [''],
          ['Café en Producción'],
          ['Fungicidas, Insecticidas y Foliares'],
          ['Break Thru 100SL', '120ml', '2', '6cc', '0.6 L'],
          ['Sergomil', 'Litro', '1', '2 copas', '0.5 L'],
          ['Opus 12.5SC', 'Litro', '2', '1 copa', '0.35 L'],
          ['Opera 18.3SE', 'Litro', '1', '3 copas', '0.7 L'],
          ['Curyom 55EC', '100ml', '2', '10cc', '1'],
          ['Foltron Plus', 'Litro', '1', '4 copas', '1'],
          ['Biozyme', 'Litro', '1', '1 Copa', '0.25'],
          ['Poliquel Boro', 'Litro', '1', '2 copas', '0.5'],
          ['Poliquel Calcio', 'Litro', '1', '2 copas', '0.5'],
          ['K-fol', 'Kg', '1', '4 copas', '1'],

          [''],
          ['Control de Malezas'],
          ['Biophase', '225cc', '2', '10cc', '1'],
          ['Glifo One 36SL', 'Litro', '2', '6 copas', '1.5'],
          [''],
          ['Fertilización'],
          ['Fastrac 17-5-21', '43kg', '1', '3.5 Onz / Planta', '7qq'],
          [''],
          [''],
        ],
      },
    },
  },
];
